data:
  train_data: "data/train/*.png"
  test_data: "data/test/*.png"
  batch_size: 8
train:
  gen_learning_rate: 0.00001
  dis_learning_rate: 0.000001
  gen_min_loss: -1.0
  dis_min_loss: -1.0
  num_of_epochs: 50000
  val_data_percentage: 0.3
  epochs_between_val: 500
generator:
  load_path: "saved_models/generator.pth"
  save_to: "saved_models/generator.pth" 
  in_features: 1024
discriminator:
  load_path: "saved_models/discriminator.pth"
  save_to: "saved_models/discriminator.pth" 
real_label: 1
fake_label: 0
generator_fake_label: 1
